### ISSUE TITLE
syntax error near unexpected token 'fi'

### ISSUE THREAD

**Issue by radarsymphony** [tiredofit/docker-nginx-php-fpm#20]
Hi there, 

I am running your docker tiredofit/freescout:latest image, I noticed the following error is recurring throughout the docker logs on startup: 
```
[container-name]-app          | /assets/defaults/20-php-fpm: line 44: syntax error near unexpected token `fi'
[container-name]-app          | /assets/defaults/20-php-fpm: line 44: `fi'
```
I am posting in this repo instead of freescout as it looks like it might be referencing this line: 
https://github.com/tiredofit/docker-nginx-php-fpm/blob/e2100fcee4801c6732dc0dc02b178a62e16a4f64/install/assets/defaults/20-php-fpm#L44

When I search this repo for mentions of PHP_ENABLE_REDIS, which is part of the conditional statement, I only find it in the [CHANGELOG](https://github.com/tiredofit/docker-nginx-php-fpm/blob/10e571a4e1c2baf69b2f5617f79bdc36d8c4db23/CHANGELOG.md#changed-19), [README](https://github.com/tiredofit/docker-nginx-php-fpm/blob/89f363321bc00138159267fe619e5d97faf6fe75/README.md#enabling--disabling-specific-extensions), and the line above from [20-php-fpm](https://github.com/tiredofit/docker-nginx-php-fpm/blob/e2100fcee4801c6732dc0dc02b178a62e16a4f64/install/assets/defaults/20-php-fpm#L44). 

It looks like the issue arises from there being no default set (e.g. PHP_ENABLE_REDIS=FALSE) in /assets/defaults/20-php-fpm. Should there be one, or should I be setting that in my docker-compose.yml?

**Comment by tiredofit** [comment]
Can you tell me what version of nginx-php-fpm is the base of your image that you are having problems with? 
You can find it by entering in the container and executing `head -n1 /assets/.changelogs/tiredofit_docker-nginx-php-fpm.md`

I believe this was fixed as I am looking at that `20-php-fpm` defaults file and it is validating in a shell checker.

FWIW igbinary is a serializer that is a dependency for certain caching destinations such as memcached and redis. While the dependency is installed when using a package manager, I disable its usage unless absolute necessary, hence those condition statements in the default area. Alternatively I could tell people to enable `IGBINARY` when they enabled that extension, but I can't always count on people reading instructions.

**Comment by radarsymphony** [comment]
Thanks for your time and quick response. You are right the issue has been fixed. I am running an old version:  6.1.21 
I updated the base image and now the error is gone. Thanks again.

**Comment by tiredofit** [comment]
Great! 
Not so fast. Problem that you were speaking originally about was with Freescout:latest which is a descendent of this image, I don't believe there were updates to that image for quite some time, except for up until 2 or 3 days ago. Regardless, I just built a brand new image of :latest of that image. That and other descendant images sometimes get pinned to specific versions of the upstream images which is probably what you were seeing. I am evaluating if I want to weekly rebuild :latest images for those descendants to make sure we zap any parent/upstream bugs, but that also introduces alot of chaos as well for users who don't use tagged images.
