### ISSUE TITLE
Best way to push logs to stdout/stderr ? 

### ISSUE THREAD

**Issue by chuckienorton** [tiredofit/docker-nginx-php-fpm#28]
Hello, 

what is the recommended method for pushing logs to /dev/stdout ? 

I tried this method: 

```
RUN ln -sf /dev/stdout /www/logs/php-fpm/access.log
RUN ln -sf /dev/stdout /www/logs/php-fpm/error.log
```

But that results in an error that the files/folders there don't exist. Maybe they are created after logs start? 

Let me know if there is a standardized way to do this. 

Thanks!

**Comment by tiredofit** [comment]
I think you would want to start with 
`CONTAINER_LOG_LEVEL=DEBUG` to allow console output to occur for each process.
Then set `PHP_LOG_LOCATION=/dev`

Then `PHP_LOG_ACCESS_FILE="/stdout"` and `PHP_LOG_ERROR_FILE=/stdout` _should!?!?_ work.. YMMV.

**Comment by chuckienorton** [comment]
Ooh ok. Thank you for the quick response!!

I think you meant PHP_LOG_LEVEL (instead of CONTAINER_LOG_LEVEL) correct? 

Anyway the below didn't work for me on DigitalOcean app containers. 
```
# Base Vars
ENV PHP_LOG_LEVEL=debug
ENV PHP_LOG_LOCATION=/dev
ENV PHP_LOG_ACCESS_FILE=/stdout
ENV PHP_LOG_ERROR_FILE=/stderr

FROM tiredofit/nginx-php-fpm:debian-8.1

# Set Working Directory
WORKDIR /www/html
...
```
But no expectation for your help - i'll report back here if I figure out how to get the error logging to work.

**Comment by tiredofit** [comment]
No I was right on the CONTAINER_LOG_LEVEL=DEBUG .. If set to something other I use that to hide the stdout/stderr output of any processes that startup, it may affect your ability to route to stdout - Give it a try though without, but that's my thinking. In future I can see about adding a PHP_FPM_LOG_TYPE environment variable with options of `CONSOLE` or `FILE` in future, should be easy enough.
