### ISSUE TITLE
best way to setup papertrail...

### ISSUE THREAD

**Issue by chuckienorton** [tiredofit/docker-nginx-php-fpm#32]
Hello, 

i am planning on setting up papertrail to watch for all system logs. I'd love for nginx logs, php logs, and application logs to all go to papertail. 

According to https://docs.docker.com/config/containers/logging/syslog/ - it looks like it's possible to send all syslogs to a forwarded adddress/port, which is also what papertail says to do. 

I haven't actually attempted to add this to my Dockerfile yet. Since you have such an opinionated docker container (which i love by the way!) i thought i'd ask before installing. How do you recommend doing it?

**Comment by tiredofit** [comment]
Log analysis - the final frontier! 

Knowing what we've talked about in the past, you could certainly redirect your logs to stderr/stdout and then rely on the docker logging output to send the json output to a syslog server. I tend to take a conservative approach - In my environment I ship

- Docker logs (aka the output of `docker logs container-name`
- My container logs (any of my output of INFO/NOTICE/ERROR etc)
- Application logs (`nginx-access.log` `nginx-error.log` `whatever_else.log` .

via a tool called [Fluent bit](https://fluentbit.io/). I've built some automatic routines that can detect if you have new log files to ship by means of adding them into the flat file "log rotation" schemes. This allows to have the best of both worlds. I have the flat log files that can be backed up on my backup system and parsed in a more "oldschool" format, and then can use the forwarding features of Fluentbit to whatever output. Hint, my output is Loki - which then gets read by Grafana. I only have Loki output now but whatever you find on the Although we can easily build in more "[output](https://docs.fluentbit.io/manual/pipeline/outputs)" to wherever the destination is.

I don't have a syslog server Docker image but I am sure they exist, and I also could be contracted to have something built that would meet your needs, and therefore also give back to the community for others in same situations.

Definitely my images are opinionated, based on my own (huge) environment, but they base images are flexible enough to support additional use cases with ease. I'm sure there are tonnes of other ways to do it, and some would argue at my "fat" approach as opposed to a "microservice" approach might be better, but it all really depends on the overall use case.. Apples vs oranges. Have a peek at the base image [README](https://github.com/tiredofit/docker-alpine/blob/master/README.md) to see how log shipping works in these containers..

**Comment by chuckienorton** [comment]
OK! Thanks sir. Very informative as always! 

I'll talk to my team about this. As it is, we can have the app (laravel) send it's own logs to papertrail easily, and the other files - as you mentioned - are available within the container.  For now we'll just move forward and contact you if we want to setup output that is papertrail compatable. 

Thanks again as always!!
