### ISSUE TITLE
opcache.max_accelerated_files=5413

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-nginx-php-fpm#44]
**Description of the feature**
currently, opcache.max_accelerated_files seems to have a fixed value. My nextcloud is complaining that the #of files in the cache exceeds this limit. Would it be possible to make this parameter configurable (maybe along with some other .ini parameters)?

**Beneftits of feature**
Bigger sites might benefit from opcache and other .ini tuning settings

**Comment by tiredofit** [comment]
Yes, absolutely. Will do something about it in the next couple of days.

**Comment by tiredofit** [comment]
`7.2.0` adds 4 new environment variables to change related to APC and OPCache.

I've also started rebuilds on latest on the most pulled images: `tiredofit/wordpress`, `tiredofit/bookstack`, `tiredofit/freescout`, `tiredofit/fusiondirectory:1.4`, and versioned builds for `tiredofit/nextcloud:2[3,4,5]` - Let me know how this works out.

**Comment by joergmschulz** [comment]
As expected - it works perfect for Nextcloud 24. Also, the newly wordpress image works fine. So we can derive that the others work as well....
