### ISSUE TITLE
Plugins touted as enabled, yet are unconfigured

### ISSUE THREAD

**Issue by frebib** [tiredofit/docker-nginx-php-fpm#6]
From the latest, `docker-fusiondirectory` image, which has https://github.com/tiredofit/docker-nginx-php-fpm/commit/15105a8c71c0bff036dd3e5b28c3ec478b9588a4 from this repo as a base, I see this message in the logs

```
[cont-init.d] 20-php-fpm: executing...
[NOTICE] ** [php-fpm] PHP-FPM Preparing to start with the following plugins enabled: apcu, bcmath, ctype, curl, dom, gd, gettext, iconv, imagick, imap, intl, json, ldap, mbstring, mcrypt, mysqli, mysqlnd, opcache, openssl, pdo, pdo_mysql, pgsql, phar, session, xml, xmlreader, zlib
[cont-init.d] 20-php-fpm: exited 0.
```

yet the configuration files that enable these plugins are all missing
```
bash-4.4# cd /etc/php7/conf.d/
bash-4.4# ls -al
total 24
drwxr-xr-x    2 root     www-data         6 Apr 21 17:31 .
drwxr-xr-x    4 root     www-data         6 Apr 21 17:31 ..
-rwxr-xr-x    1 root     www-data        18 Jan 27 22:54 01_imap.ini
-rwxr-xr-x    1 root     www-data        20 Dec 25  2018 mcrypt.ini
-rwxr-xr-x    1 root     www-data        51 Apr 21 17:31 smtp.ini
-rwxr-xr-x    1 root     www-data        18 Apr 21 17:31 timezone.ini
```

The key clue to this puzzle is that when trying to load fusiondirectory, I'm greeted by this helpful error, which wasn't present before
```
Fatal error: Uncaught Error: Call to undefined function session_name() in /www/fusiondirectory/include/class_session.inc:222 Stack trace: #0 /www/fusiondirectory/html/index.php(114): session::start() #1 {main} thrown in /www/fusiondirectory/include/class_session.inc on line 222
```

I think the logic for deleting those files could be wrong?

**Comment by frebib** [comment]
https://gist.githubusercontent.com/frebib/3a21625d4d776a42436058da248bbc2d/raw
Debug logs show the files being deleted

**Comment by tiredofit** [comment]
Oh dear. Yes, I've mucked it up badly. Definitely not my week.

**Comment by tiredofit** [comment]
Alright - I had a feeling this was going to haunt me and didn't catch it in my testing. I've pushed new copies and Docker Hub will go through the task of rebuilding everything yet another time.

**Comment by frebib** [comment]
Seems to be fixed with the latest `fusiondirectory` build, thanks :)
