### ISSUE TITLE
How to add scripts to crontab?

### ISSUE THREAD

**Issue by Stefan39** [tiredofit/docker-nginx-php-fpm#63]
Hi Dave, on this issue https://github.com/tiredofit/docker-nginx-php-fpm/issues/29 you commented to add a script to crontab use `CRON_ARTISAN` env, but what can i do if I have more than one line to adding?

**Comment by tiredofit** [comment]
You could seperate the commands with a `;`. Alternatively map another volume inside the container and execute your commands as a bash script? If so if you want access to the container environment variables inside the script use: `#!/command/with-contenv bash` as your first line..

**Comment by Stefan39** [comment]
Ok i have found a solution for this. I'm link my crontab file in docker-compose.yml to /assets/cron/project and all cronjobs runs fine.

Thanks for your support and great work! Will use this image for all my symfony workings

**Comment by tiredofit** [comment]
Awesome :) If there is something specific you need as a feature let me know, it should be fairly easy to work in. 

I have a couple updates coming shortly that will allow for increased performance if that is what you are after. I'm also investing time into https://github.com/tiredofit/docker-unit-php which cuts out the nginx/php-fpm layer and just serves PHP directly to what is looking like a large performance and resource boost. It doesn't have all the authentication and fancy features as the nginx package, but my hope is that it will be able to replace 50% of my running sites.
