### ISSUE TITLE
Issue with Installing and Enabling Memcached Extension on tiredofit/nginx-php-fpm:8.2-alpine

### ISSUE THREAD

**Issue by dharmeshmp** [tiredofit/docker-nginx-php-fpm#77]
### Description
I'm experiencing issues installing and enabling the `memcached` extension on the `tiredofit/nginx-php-fpm:8.2-alpine` image. The process fails due to a missing `phpize82` command, which `pecl` expects when attempting to install the extension. 

I've followed various approaches to resolve this, including creating symbolic links to `phpize`, but these attempts have not been successful.

### Expected Behavior
I expected to be able to install and enable the `memcached` extension using the `pecl install memcached` command without errors.

### Actual Behavior
The installation fails with the following error:

```
running: phpize82
sh: phpize82: not found
ERROR: `phpize` failed
```

### Steps to Reproduce
1. Use `tiredofit/nginx-php-fpm:8.2-alpine` as the base image.
2. Run the following commands to attempt to install `memcached`:
   ```Dockerfile
   RUN apk update && \
       apk add --no-cache libmemcached-dev zlib-dev alpine-sdk autoconf && \
       pecl channel-update pecl.php.net && \
       pecl install memcached && \
       echo "extension=memcached.so" > /etc/php8/conf.d/memcached.ini
   ```
3. Observe the error related to `phpize82`.

### Dockerfile Snippet

Here is the Dockerfile snippet I’m using:

```Dockerfile
FROM tiredofit/nginx-php-fpm:8.2-alpine

RUN apk update && \
    apk add --no-cache libmemcached-dev zlib-dev alpine-sdk autoconf && \
    pecl channel-update pecl.php.net && \
    pecl install memcached && \
    echo "extension=memcached.so" > /etc/php8/conf.d/memcached.ini
```

### Environment
- Image: `tiredofit/nginx-php-fpm:8.2-alpine`
- PHP Version: 8.2

### Additional Context
The `phpize` command appears to be available, but `pecl` specifically looks for `phpize82`. I attempted to resolve this by creating a symbolic link to `phpize` as follows:

```Dockerfile
ln -s /usr/bin/phpize /usr/bin/phpize82
```

Unfortunately, this approach did not resolve the issue, and the `memcached` extension still fails to install.

Would it be possible to include native support for the `memcached` extension in this image, or is there an alternative solution to enable this extension?

Thank you for your assistance!

**Comment by tiredofit** [comment]
What happens when you use `PHP_ENABLE_MEMCACHED=TRUE` as an environment variable when starting the container? It should already be installed and now activated with that command..

**Comment by dharmeshmp** [comment]
Thank you for the suggestion to use `PHP_ENABLE_MEMCACHED=TRUE`—it worked perfectly! It would be very helpful to include this information in the documentation for others setting up memcached with the image.

Regarding MongoDB, I didn’t find a similar environment variable for enabling the extension. I was able to get it working by manually installing the extension in the Dockerfile, but it would be great if you could clarify whether there’s a native way to enable MongoDB, similar to how memcached is activated.

Thank you for your help, and I’d love to see this information added to the documentation!

**Comment by dharmeshmp** [comment]
Thank you for the clarification! I appreciate the tip to check available extensions with `php-ext list all` to identify environment variables for enabling modules.

While I did see that line in the README, it might be helpful for future users if there was a specific section listing common extensions and their corresponding environment variables. This could make it quicker to activate frequently used modules like memcached or MongoDB without having to explore inside the container. 

Thanks again for the help—everything’s running smoothly now!
