### ISSUE TITLE
[BUG] nginx: [emerg] invalid port in upstream ":" in /etc/nginx/nginx.conf.d/php-fpm.conf:1

### ISSUE THREAD

**Issue by madmath03** [tiredofit/docker-nginx-php-fpm#9]
While testing https://github.com/tiredofit/docker-self-service-password, I got this error in logs `nginx: [emerg] invalid port in upstream ":" in /etc/nginx/nginx.conf.d/php-fpm.conf:1` and the following file content:
```
fastcgi_pass :;
fastcgi_read_timeout ;
```

This generates code seems to be the issue:
https://github.com/tiredofit/docker-nginx-php-fpm/blob/5c6cf78a5e32e9b24ca45613d7ff2eac583de8ad/install/etc/nginx/nginx.conf.d/php-fpm.conf#L1-L2

I believe the variables used should be `PHP_FPM_HOST` and `PHP_FPM_LISTEN_PORT`.

**Comment by tiredofit** [comment]
Hi there. Please try an earlier tagged version if possible. Docker Hub has been running on a loop and built descendent images before the base images fixed up, thus throwing this error with blank values. It's been going on a few days now, and hopefully getting back to normal in the next few as well?

**Comment by tiredofit** [comment]
I'll also push up some manual images tomorrow morning if it isn't fixed by then.
